FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PORT=80

RUN apt-get update \
    && apt-get install -y --no-install-recommends tzdata \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY stage-4/main.py /app/main.py
COPY stage-4/assets /app/assets

EXPOSE 80

CMD ["python", "/app/main.py"]
